# Generated by Django 5.2.5 on 2025-08-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Ww', 'Women wear'), ('Mw', 'Men wear'), ('S', 'Shoe')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('O', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
