# Generated by Django 5.2.5 on 2025-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'All'), ('MW', 'Men wear'), ('WW', 'Women wear')], max_length=2),
        ),
    ]
