# Generated by Django 5.2.5 on 2025-09-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_status_alter_item_price_payment_order_payment_and_more'),
    ]

    operations = [
    ]
