# Generated by Django 5.2.5 on 2025-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250915_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='new', max_length=254),
            preserve_default=False,
        ),
    ]
