# Generated by Django 5.2.5 on 2025-09-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category_item_label'),
        ('core', '0003_alter_item_category'),
    ]

    operations = [
    ]
